name: Ubuntu 18.04 (Docker Minimal)
on: [push, pull_request]
env:
  CONTAINER: ubuntu:18.04
  # Note: unfortunately, we cannot just use `jobs.build.container: ubuntu:18.04`,
  # otherwise we cannot use GitHub-provided actions (checkout, cache, etc.) as
  # they rely on Node20 which isn't available on Ubuntu 18.04.
  # See: https://github.com/actions/checkout/issues/1590

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install Dependencies
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ env.CONTAINER }}
        run: |
          apt-get update
          apt-get install -y cmake build-essential libfreetype6-dev libharfbuzz-dev

    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ env.CONTAINER }}
        run: |
          mkdir build
          cd build
          cmake --version
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
