name: Ubuntu 18.04 (Docker Minimal Custom Image)
on: [push, pull_request]
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

jobs:
  build:
    runs-on: ubuntu-latest
    container: dalboris/test-cpp-github-actions-docker-ubuntu-18.04-minimal
    steps:

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y libharfbuzz-dev

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake --version
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
