name: Ubuntu 18.04 (Docker Minimal Custom Image)
on: [push, pull_request]
env:
  CONTAINER: dalboris/test-cpp-github-actions-docker-ubuntu-18.04-minimal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    # We manually start a container and execute scripts in it instead of using `jobs.build.container`,
    # otherwise we couldn't use GitHub-provided actions (checkout, cache, etc.) as they rely on Node20
    # which would not necessarily be available on some containers (e.g., Ubuntu 18.04).
    #
    # See: https://github.com/actions/checkout/issues/1590
    #
    - name: Start Docker Container
      run: |
        docker pull $CONTAINER
        docker run --name build-container -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null

    - name: Install Dependencies
      env:
        SCRIPT: |
          apt-get update
          apt-get install -y libharfbuzz-dev
      run: docker exec build-container bash -c "$SCRIPT"

    - name: Build
      env:
        SCRIPT: |
          cd /workspace && mkdir build && cd build
          cmake --version
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      run: docker exec build-container bash -c "$SCRIPT"
