name: Ubuntu 18.04 (Docker Minimal Custom Image)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: dalboris/ubuntu-18.04-test-cpp-github-actions
    steps:

    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake --version
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
