name: Ubuntu 18.04 (Docker Minimal)
on: [push, pull_request]
env:
  CONTAINER: ubuntu:18.04
  # Note: unfortunately, we cannot just use `jobs.build.container: ubuntu:18.04`,
  # otherwise we cannot use GitHub-provided actions (checkout, cache, etc.) as
  # they rely on Node20 which isn't available on Ubuntu 18.04.
  # See: https://github.com/actions/checkout/issues/1590

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Pull Docker Image
      run: |
        docker pull $CONTAINER

    - name: Start Container
      run: |
        docker run --name cnt -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null

    - name: Install Dependencies
      run: |
        docker exec cnt apt-get update
        docker exec cnt apt-get install -y cmake build-essential libfreetype6-dev libharfbuzz-dev

    - name: Build
      run: |
        docker exec cnt mkdir build
        docker exec cnt cd build
        docker exec cnt cmake --version
        docker exec cnt cmake .. -DCMAKE_BUILD_TYPE=Release
        docker exec cnt cmake --build .
